# tasks file
---
- name: install | dependencies (pre)
  ansible.builtin.apt:
    name: "{{ haproxy_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  when: "ansible_os_family == 'Debian'"
  tags:
    - haproxy-repository-install-dependencies

- name: install | add repository from PPA and install its signing key
  ansible.builtin.apt_repository:
    repo: "{{ haproxy_ppa }}"
    update_cache: true
  when:
    - haproxy_use_ppa | bool
    - "ansible_os_family == 'Debian'"
  tags:
    - haproxy-install-add-repository

- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  when: "ansible_os_family == 'Debian'"
  tags:
    - haproxy-install-dependencies

- name: install | additional
  ansible.builtin.apt:
    name: "{{ haproxy_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  when: "ansible_os_family == 'Debian'"
  tags:
    - haproxy-install-additional

- name: install haproxy (RHEL)
  dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  when: "ansible_os_family == 'RedHat'"
  tags:
    - haproxy-install-dependencies

- name: install | additional (RHEL)
  dnf:
    name: "{{ haproxy_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  when: "ansible_os_family == 'RedHat'"
  tags:
    - haproxy-install-additional

# RH package doesn't create the /etc/haproxy/errors dir
- name: Create symlink to /etc/haproxy/errors dir (RHEL)
  ansible.builtin.file:
    src: /usr/share/haproxy
    dest: /etc/haproxy/errors
    state: link
  when: "ansible_os_family == 'RedHat'"
  tags:
    - haproxy-install-dependencies
